Remove the default 'Titillium' font from the Angular base project
IgniteUI/igniteui-cli pull request #1203
Opened 2024-02-13 08:59 UTC by viktorkombov

Closes # .  

Additional information related to this pull request:

2024-02-14 13:35 UTC, Lipata requested changes

2024-02-14 13:35 UTC, Lipata commented on packages/igx-templates/igx-ts-legacy/projects/_base/files/src/index.html
> -  <link href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400,600,700" rel="stylesheet">
@viktorkombov only this change should be left. The other changes I guess can come from an old version of the branch. Do you want us to change the client part of the CodeGen, or you have a plan to do it?

2024-02-22 12:59 UTC, wnvko approved these changes

2024-02-22 14:05 UTC, Lipata approved these changes

2024-02-22 14:46 UTC, merged