indentation across igr-ts projects
IgniteUI/igniteui-cli pull request #1223
Opened 2024-03-13 12:04 UTC by onlyexeption

Closes #1219   

Additional information related to this pull request:

2024-03-13 14:38 UTC, gedinakova requested changes
The only place remaining is the return statement in main.tsx: 
`Number.isNaN = Number.isNaN || function(value) {
    return value !== value;
}`

2024-03-13 15:08 UTC, wnvko requested changes

2024-03-13 15:08 UTC, wnvko commented on packages/cli/templates/react/igr-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.tsx
>      const title = 'Linear Gauge';
from line 8th to line 58th there is two extra spaces.

2024-03-14 15:52 UTC, gedinakova approved these changes

2024-03-15 07:51 UTC, merged