add test files for app component in WC and Angular
IgniteUI/igniteui-cli pull request #1286
Opened 2024-07-23 05:23 UTC by onlyexeption

Closes [30492](https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30492/) in CodeGen

Additional information related to this pull request:

2024-07-23 06:54 UTC, wnvko requested changes
Adding spec file to `_base` project will add this file to all the projects in `projects` folder both for Angular and WebComponents. All these projects imports routing and some other ignite-ui components which are not added in the spec file. IMO for each project we should create specific spec file.

2024-07-23 06:54 UTC, wnvko commented on packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app.component.spec.ts
> +describe('MasterViewComponent', () => {
`AppComponent` instead of `MasterViewComponent`?

2024-07-23 06:54 UTC, wnvko commented on packages/igx-templates/igx-ts/projects/_base/files/src/app/app.component.spec.ts
> +describe('MasterViewComponent', () => {
`AppComponent` instead of `MasterViewComponent`?

2024-07-25 10:55 UTC, onlyexeption commented
> Adding spec file to `_base` project will add this file to all the projects in `projects` folder both for Angular and WebComponents. All these projects imports routing and some other ignite-ui components which are not added in the spec file. IMO for each project we should create specific spec file.

For igx-ts and igx-ts-legacy:

I added RouterTestingModule to the test imports in the base template. Now the `empty` and `base` (_base and _base_with_home) projects will have it imported in their spec files.  The side-nav and side-nav-auth have their own app spec files.

For webcomponents, I double checked different component's test files as well as the CodeGen template. They have the same structure everywhere so I don't think its necessary to create separate app.test.ts files.

2024-07-30 10:50 UTC, jackofdiamond5 approved these changes

2024-07-30 12:29 UTC, Lipata approved these changes

2024-07-30 12:29 UTC, merged