resolve vulnerability alerts
IgniteUI/igniteui-cli pull request #1331
Opened 2024-11-04 06:59 UTC by Hristo313

Resolve Vulnerability alerts in the igniteui-cli (dependabot and code scanning alerts)

2024-11-04 08:51 UTC, kdinev commented on packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/DataGridSharedData.ts
> +      const age: number = Math.round(this.getSecureRandomNumber(20, 40));
I'm pretty sure that these about the random numbers in dummy data can safely be marked as false positives.

2024-11-05 08:47 UTC, Lipata approved these changes

2024-11-05 08:53 UTC, Lipata requested changes

2024-11-05 08:53 UTC, Lipata commented on packages/core/packages/PackageManager.ts
> +			spawnSync(managerCommand, args, { stdio: "pipe", encoding: "utf8" });
I wonder if its worth adding spawnSync to Util, and wrap it in a try-catch, like it is with execSync?

2024-11-05 13:18 UTC, Lipata approved these changes

2024-11-05 13:19 UTC, merged