Fixing errors related to strict templates
IgniteUI/igniteui-cli pull request #854
Opened 2021-07-15 21:36 UTC by dafo

Closes #847 .  

Additional information related to this pull request:

2021-07-19 09:16 UTC, wnvko requested changes
Awesom Grid comments added.
Note - all the files have mixed tabs and spaces for indentation. There should not be any tabs, only spaces.

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	// eslint-disable-next-line @typescript-eslint/naming-convention
you can remove this warning workaround - this should not be needed now

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	get hideAthleteNumber() {
set type to `boolean`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	get hideBeatsPerMinute() {
set type to `boolean`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public ngOnInit() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public ngAfterViewInit() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public ngOnDestroy() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public getTrophyUrl(index: number) {
set type to `string`. You should return empty string in the end of the method.

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public getSpeedeData(minutes?: number): any[] {
after adding `SpeedDescriptor` this should return `SpeedDescriptor[]`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	  const speed: any[] = [];
set this to `SpeedDescriptor[]`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public addSpeedeData(athlete: Athlete, minutes?: number): any[] {
this should return `SpeedDescriptor[]`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public onResize(event: any) {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public filter(event: Event) {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public showAlert(element: ElementRef) {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public hideAlert() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	private generateRandomNumber(min: number, max: number) {
set type to `number`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	private ticker() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	private manageRace() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	private updateData() {
set type to `void`

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public operate(data?: any[]): IgxSummaryResult[] {
data should be of type `number[]` as this is on number type column

2021-07-19 09:16 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public operate(data?: any[]): IgxSummaryResult[] {
data should be of type `number[]` as this is on number type column

2021-07-19 09:18 UTC, wnvko requested changes

2021-07-19 09:18 UTC, wnvko commented on packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
> +	public addSpeedeData(athlete: Athlete, minutes?: number): any[] {
there is a typo in the method name
```suggestion
	public addSpeedData(athlete: Athlete, minutes?: number): any[] {
```

2021-07-21 06:27 UTC, wnvko approved these changes
We should log separate issue to clean up the samples code. There are a lot more not strongly typed items in the code, mixed indentations and so on.

2021-07-26 12:28 UTC, valadzhov commented
There are multiple errors when I try to build a project created with the templates:
![image](https://user-images.githubusercontent.com/9549439/126988585-8621e06a-0cab-47bc-9006-6511154602ed.png)

2021-07-28 06:21 UTC, wnvko approved these changes

2021-07-28 07:23 UTC, merged